# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
tagline:          'CE Programming docs'
description:      'Native programming documentation for TI CE calculators'
url:              "https://ce-programming.github.io"
baseurl:          "/documentation"

paginate:         5

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
# gems:
  # - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

github:
  repo:           "https://ce-programming.github.io/documentation"
