# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
tagline:          'CE Programming docs'
description:      'Native programming documentation for TI CE calculators (84+CE / 83PCE)'
url:              "https://ce-programming.github.io"
baseurl:          "/documentation"

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           "https://ce-programming.github.io/documentation"
